version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jefte27/linuxtips-giropops-senhas:1.0
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis-service
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - redis
    networks:
      - giropops

  redis:
    image: "redis:alpine"
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - giropops
  
networks:
  giropops: 
     driver: bridge